"""
AI Service abstraction - LLM only reasons/recommends, never executes.

Gemini API via google-generativeai. Falls back to deterministic mock when no key.
Implements retry with exponential backoff, strict JSON parsing, Pydantic validation,
and cost-control (spam filter, input truncation) before calling LLM.
"""
import time
import json
import re
import logging
from typing import Optional

from pydantic import ValidationError

from app.core.config import settings
from app.models.schemas import AIAnalysis, ClassificationEnum, ActionTypeEnum
from app.core.logging import logger

# ---------- Prompt (LLM 100% scalable — no manual keyword lists, team via embedding + source context) ----------
SYSTEM_PROMPT = """You are InboxOps triage AI — LLM 100% determines classification, extraction, and DRAFT RESPONSE generation. NEVER invent — use null if unknown. DRAFT_RESPONSE MUST BE GENERATED BY YOU (LLM), not a template.

Categories: sales (pricing/demo/partnership), support (help/bug/complaint), junk (spam), insufficient_information (too vague), other (career/job/recruitment/hiring at BEDA, legal, partnership, general). Confidence 0-1, high only if clear. priority low|medium|high from urgency (high if deadline/error blocking, low if vague). Consider source: email=formal business (polite, detailed), website=form lead often sales/marketing, messaging=short chat often urgent support (concise). IMPORTANT: job/career/recruitment/hiring/joining team at BEDA → classification "other", NOT sales.

Actions: CREATE_LEAD, UPDATE_CONTACT, CREATE_SUPPORT_CASE, REQUEST_MORE_INFORMATION, MARK_AS_JUNK.

Extract: contact{name,email,phone}, company{name,size e.g. "200 employees"}, intent(1 sentence), intent_keywords[3-6 verbatim lowercase keywords from message, e.g. ["pricing","demo","automation"]], priority, missing_information[budget,timeline,company,business_need,contact_details,phone,use_case,company_size], draft_response.

DRAFT_RESPONSE RULES (LLM-generated, 1-3 sentences, null only if junk, never promise send, never auto-send):
- MUST be contextual and personalized: use sender name, company if known, and intent_keywords/intent. Do NOT always start with "Thanks for reaching out" — vary openings: "Hi {name},", "Hello {name}, thanks for...", "Appreciate your message about...", "Sorry to hear about...".
- sales: acknowledge specific interest (e.g. "AI automation for support"), mention company, ask for budget/timeline or next step.
- support: empathize, acknowledge the specific issue, say team will investigate, ask for order_id/error details if missing.
- insufficient_information: ask specific missing fields (company, use case, timeline) with a helpful question.
- Keep under 3 sentences, warm and professional, match source tone (email formal, chat concise).
- Never hallucinate phone/budget/company if null.

Rules: Return ONLY valid JSON, no markdown. No hallucinated company/phone/budget. If unsure, null + add to missing_information. intent_keywords must be words that appear in message (or close paraphrase), 3-6 items. missing_information is [] if none. Priority high only if urgent/blocking. Weigh source lightly as context, not override.

Schema: {"classification":"sales|support|junk|insufficient_information|other","confidence":0.0-1.0,"contact":{"name":str|null,"email":str|null,"phone":str|null},"company":{"name":str|null,"size":str|null},"intent":str|null,"intent_keywords":[str],"priority":"low|medium|high|null","missing_information":[str],"recommended_action":"CREATE_LEAD|UPDATE_CONTACT|CREATE_SUPPORT_CASE|REQUEST_MORE_INFORMATION|MARK_AS_JUNK","draft_response":str|null}

Examples:
sales: {"classification":"sales","confidence":0.94,"contact":{"name":"John Smith","email":"john@acme.com","phone":null},"company":{"name":"Acme","size":"200 employees"},"intent":"Interested in AI automation for customer support","intent_keywords":["ai automation","customer support","200 employees"],"priority":"medium","missing_information":["budget","timeline"],"recommended_action":"CREATE_LEAD","draft_response":"Hi John, thanks for exploring AI automation for Acme's support team (200 employees). Could you share your expected timeline and budget range so we can tailor a demo?"}
support: {"classification":"support","confidence":0.89,"contact":{"name":"Nadia Rahman","email":"nadia@shop.id","phone":null},"company":{"name":null,"size":null},"intent":"Cannot log in, error 500 when accessing dashboard","intent_keywords":["cannot log","error 500","dashboard"],"priority":"high","missing_information":["order_id"],"recommended_action":"CREATE_SUPPORT_CASE","draft_response":"Hi Nadia, sorry you're hitting an error 500 on the dashboard — our support team will look into it right away. Could you share any screenshot or order ID?"}
insufficient: {"classification":"insufficient_information","confidence":0.91,"contact":{"name":"Alex","email":null,"phone":null},"company":{"name":null,"size":null},"intent":"Vague enquiry, insufficient details","intent_keywords":["interested","services"],"priority":"low","missing_information":["company","business_need"],"recommended_action":"REQUEST_MORE_INFORMATION","draft_response":"Hi Alex, thanks for your interest! Could you tell us a bit about your company and the challenge you're hoping to solve?"}
hr_other: {"classification":"other","confidence":0.92,"contact":{"name":"Daniel Morgan","email":"daniel@ex.com","phone":null},"company":{"name":"BEDA","size":null},"intent":"Interested in job opportunities at BEDA","intent_keywords":["job opportunities","BEDA","openings"],"priority":"low","missing_information":["resume","position"],"recommended_action":"REQUEST_MORE_INFORMATION","draft_response":"Hi Daniel, thanks for your interest in joining BEDA. Our HR team will review your inquiry and share current openings — feel free to send your CV and preferred role."}"""

# ---------- Deprecated deterministic filters (kept only as fallback, LLM 100% path skips them) ----------
def is_obvious_spam(message: str) -> bool:
    """Deprecated: LLM 100% now determines junk. Kept as safety-net fallback if LLM unavailable."""
    if not settings.LLM_ONLY_CLASSIFICATION:
        low = message.lower()
        for kw in settings.SPAM_KEYWORDS:
            if kw.lower() in low:
                return True
        if len(low) < 15 and ("http://" in low or "https://" in low):
            return True
    return False


def deterministic_fast_path(sender_name: str, sender_email: str, message: str) -> Optional[AIAnalysis]:
    """Deprecated: LLM 100% path bypasses this. Only used when LLM_ONLY_CLASSIFICATION=False."""
    if settings.LLM_ONLY_CLASSIFICATION:
        return None
    low = message.lower().strip()
    if len(low) < 80 and not any(k in low for k in ["price", "pricing", "demo", "support", "help", "issue", "bug", "error", "budget", "timeline"]):
        vague_phrases = ["interested in your services", "interested", "hello", "hi,", "more info", "tell me more"]
        if any(p in low for p in vague_phrases) or len(low.split()) < 7:
            return AIAnalysis(
                classification=ClassificationEnum.insufficient_information,
                confidence=0.91,
                contact={"name": sender_name, "email": sender_email, "phone": None},
                company={"name": None, "size": None},
                intent="Vague enquiry, insufficient details",
                intent_keywords=["insufficient", "vague"],
                priority="low",
                missing_information=["company", "business_need", "contact_details"],
                recommended_action=ActionTypeEnum.REQUEST_MORE_INFORMATION,
                draft_response="Thanks for reaching out. Could you tell us a little more about your company and what problem you are looking to solve?",
            )
    support_strong = ["can't log in", "cannot log in", "error 500", "not working", "broken", "refund", "ticket", "failed to", "help me"]
    if any(k in low for k in support_strong):
        m = re.search(r"(\+?\d[\d \-\(\)]{7,}\d)", message)
        phone = m.group(1).strip() if m else None
        return AIAnalysis(
            classification=ClassificationEnum.support,
            confidence=0.92,
            contact={"name": sender_name, "email": sender_email, "phone": phone},
            company={"name": None, "size": None},
            intent="Customer seeking support assistance",
            intent_keywords=["support", "error", "login"],
            priority="high",
            missing_information=[],
            recommended_action=ActionTypeEnum.CREATE_SUPPORT_CASE,
            draft_response=f"Thanks for contacting us, {sender_name or 'there'}. Our support team will look into the issue shortly.",
        )
    return None

def truncate_input(text: str, max_len: int = None) -> str:
    max_len = max_len or settings.MAX_INPUT_LENGTH
    if len(text) > max_len:
        return text[:max_len] + " ...[truncated]"
    return text

# ---------- Cache & Rate limiter (P1) ----------
import hashlib
_response_cache: dict[str, tuple[float, AIAnalysis]] = {}  # hash -> (timestamp, result)
_last_call_per_key: dict[int, float] = {}  # key_idx -> last_call_epoch
_key_quota_exhausted: dict[int, float] = {}  # key_idx -> expiry epoch (24h)

def _is_key_exhausted(key_idx: int) -> bool:
    exp = _key_quota_exhausted.get(key_idx)
    if exp and time.time() < exp:
        return True
    if exp and time.time() >= exp:
        _key_quota_exhausted.pop(key_idx, None)
    return False

def _mark_key_exhausted(key_idx: int):
    _key_quota_exhausted[key_idx] = time.time() + 86400  # 24h
    logger.warning(f"Marking Gemini key {key_idx+1} as quota-exhausted for 24h")

def _cache_key(sender_email: Optional[str], message: str, source: str) -> str:
    safe_email = (sender_email or "").strip().lower()
    h = hashlib.sha256(f"{safe_email}|{source}|{message.strip().lower()}".encode()).hexdigest()
    return h

def _get_cached(sender_email: Optional[str], message: str, source: str) -> Optional[AIAnalysis]:
    k = _cache_key(sender_email, message, source)
    entry = _response_cache.get(k)
    if entry:
        ts, val = entry
        if time.time() - ts < settings.CACHE_TTL_SECONDS:
            return val
        else:
            _response_cache.pop(k, None)
    return None

def _set_cached(sender_email: Optional[str], message: str, source: str, result: AIAnalysis):
    k = _cache_key(sender_email, message, source)
    # Simple LRU: keep max 500 entries
    if len(_response_cache) > 500:
        # evict oldest
        oldest = min(_response_cache.items(), key=lambda x: x[1][0])[0]
        _response_cache.pop(oldest, None)
    _response_cache[k] = (time.time(), result)

def _throttle_for_key(key_idx: int):
    """Enforce rate limit per key. Sleep if needed before LLM call."""
    now = time.time()
    last = _last_call_per_key.get(key_idx, 0)
    elapsed = now - last
    min_interval = 60.0 / settings.RATE_LIMIT_RPM
    if elapsed < min_interval:
        sleep_for = min_interval - elapsed
        logger.info(f"Rate limiter: throttling key {key_idx+1} for {sleep_for:.1f}s")
        time.sleep(sleep_for)
    _last_call_per_key[key_idx] = time.time()

# ---------- Gemini client abstraction ----------
class AIServiceError(Exception):
    pass

class AIService:
    def __init__(self):
        # Reload env in case .env changed after import (e.g., after user set key)
        # Use override=False so pytest monkeypatch (which sets GEMINI_API_KEY="") is respected
        try:
            from dotenv import load_dotenv
            load_dotenv(override=False)
            import os
            # Determine API keys list: respect explicit env var presence for test mock
            has_env_override = any(k in os.environ for k in ["GEMINI_API_KEY", "GEMINI_API_KEYS", "LLM_API_KEY", "LLM_API_KEYS", "GOOGLE_API_KEY"])
            if has_env_override:
                # Collect only from env (allows monkeypatch to force empty -> mock)
                env_keys: list[str] = []
                for ek in ["GEMINI_API_KEY", "GEMINI_API_KEYS", "LLM_API_KEY", "LLM_API_KEYS", "GOOGLE_API_KEY"]:
                    ev = os.getenv(ek, "")
                    if ev:
                        env_keys.extend([p.strip() for p in ev.split(",") if p.strip()])
                # Dedup
                seen = set()
                self.api_keys = [k for k in env_keys if not (k in seen or seen.add(k))]
                # If env explicitly set but empty -> mock (test)
                if not self.api_keys and any(os.getenv(k) == "" for k in ["GEMINI_API_KEY", "GEMINI_API_KEYS"] if k in os.environ):
                    self.api_keys = []
                elif not self.api_keys:
                    # No env keys but env var existed -> treat as mock anyway (empty)
                    # Fall back to settings only if truly no override and settings has keys
                    self.api_keys = []
                # Also include settings if env not forcing mock? For real runs, .env file not in os.environ initially, so has_env_override False -> use settings
                # When has_env_override and env_keys empty but settings has keys, we still want mock for tests -> don't add settings keys
                if self.api_keys:
                    # Has explicit env keys -> use them
                    pass
                else:
                    # Check if test intentionally set empty -> force mock, don't fallback to settings
                    if any(k in os.environ for k in ["GEMINI_API_KEY", "GEMINI_API_KEYS"]):
                        self.api_keys = []
                    else:
                        self.api_keys = settings.get_llm_api_keys()
            else:
                self.api_keys = settings.get_llm_api_keys()

            # Backward compat single key
            self.api_key = self.api_keys[0] if self.api_keys else ""

            if "GEMINI_MODEL" in os.environ or "LLM_MODEL" in os.environ:
                model_env = os.getenv("GEMINI_MODEL") or os.getenv("LLM_MODEL") or ""
                self.model_name = model_env.strip() if model_env else settings.get_llm_model()
            else:
                self.model_name = settings.get_llm_model()
        except Exception:
            self.api_keys = settings.get_llm_api_keys()
            self.api_key = self.api_keys[0] if self.api_keys else ""
            self.model_name = settings.get_llm_model()

        self.is_mock = not bool(self.api_keys)
        self._client = None
        self._client_type = None  # "genai" or "google-genai"
        self._current_key_index = 0
        if not self.is_mock:
            # Init with first key; rotation will re-configure per call if needed
            # google-generativeai is required (see requirements.txt), google-genai is optional fallback
            try:
                import google.generativeai as genai
                genai.configure(api_key=self.api_keys[0])
                self._client = genai
                self._client_type = "genai"
                logger.info(f"Gemini AI initialized with model {self.model_name} ({len(self.api_keys)} key(s), google-generativeai)")
            except Exception as e1:
                # try new SDK only if available (optional, not required for mock)
                try:
                    import importlib.util
                    if importlib.util.find_spec("google.genai") is None:
                        raise ModuleNotFoundError("google.genai not installed — install google-genai or use mock mode")
                    from google import genai as new_genai
                    self._client = new_genai.Client(api_key=self.api_keys[0])
                    self._client_type = "google-genai"
                    logger.info(f"Gemini AI initialized with model {self.model_name} ({len(self.api_keys)} key(s), google-genai)")
                except ModuleNotFoundError as e2:
                    logger.info(f"Gemini SDK not fully available ({e2}) — running in mock fallback (set valid GEMINI_API_KEYS or pip install google-genai)")
                    self.is_mock = True
                    self._client = None
                except Exception as e2:
                    logger.warning(f"Failed to init Gemini (both SDKs): {e1} / {e2} — falling back to mock")
                    self.is_mock = True
                    self._client = None
        else:
            logger.info("AI Service running in MOCK mode (no GEMINI_API_KEY)")
            self.api_keys = []

    # Public entry with retry — LLM 100% (no manual keyword gate)
    def analyse(self, sender_name: str, sender_email: Optional[str], message: str, source: str = "email") -> AIAnalysis:
        # LLM 100%: skip deterministic spam/fast-path when flag enabled; LLM determines junk/support/insufficient
        if not settings.LLM_ONLY_CLASSIFICATION:
            if is_obvious_spam(message):
                logger.info("Deterministic spam filter triggered (fallback mode)")
                return AIAnalysis(
                    classification=ClassificationEnum.junk,
                    confidence=0.97,
                    contact={"name": sender_name, "email": sender_email, "phone": None},
                    company={"name": None, "size": None},
                    intent="Detected as spam/junk via fallback filter",
                    intent_keywords=["spam", "junk"],
                    priority="low",
                    missing_information=[],
                    recommended_action=ActionTypeEnum.MARK_AS_JUNK,
                    draft_response=None,
                )
            fast = deterministic_fast_path(sender_name, sender_email, message)
            if fast is not None:
                logger.info(f"Deterministic fast-path hit: {fast.classification} (fallback mode)")
                return fast

        # Cache check before LLM (24h TTL) — still valid for LLM 100% cost control
        cached = _get_cached(sender_email, message, source)
        if cached is not None:
            logger.info(f"Cache hit for {sender_email} (no LLM call)")
            return cached

        truncated = truncate_input(message)

        # helper to parse retry_delay from Gemini error
        def _parse_retry_delay(err_msg: str) -> Optional[float]:
            m = re.search(r"retry in ([\d\.]+)s", err_msg, re.I)
            if m:
                try: return float(m.group(1))
                except: pass
            m = re.search(r"seconds:\s*(\d+)", err_msg, re.I)
            if m:
                try: return float(m.group(1))
                except: pass
            m = re.search(r"retry_delay.*?(\d+)", err_msg, re.I | re.S)
            if m:
                try: return float(m.group(1))
                except: pass
            return None
        # retry loop

        last_err: Optional[Exception] = None
        for attempt in range(settings.MAX_RETRIES):
            try:
                raw = self._call_llm(sender_name, sender_email, truncated, source)
                validated = self._validate(raw)
                # Option B + Opsi A: deterministically compute suggested_team via embedding from LLM keywords+intent+source
                validated = self._enrich_routing(validated, message, source)
                _set_cached(sender_email, message, source, validated)
                return validated
            except (ValidationError, json.JSONDecodeError, AIServiceError) as e:
                last_err = e
                msg = str(e).lower()
                is_quota = any(k in msg for k in ["perday", "prepayment", "generateRequestsPerDay".lower()])
                is_rate = "perminute" in msg or ("rate" in msg and "perminute" in msg) or "GenerateRequestsPerMinute".lower() in msg
                # If quota exhausted, don't retry with same keys — all keys already tried in _call_llm, fallback to mock immediately
                if is_quota or "prepayment" in msg:
                    logger.warning(f"AI quota exhausted (no retry), will fallback to mock after attempt {attempt+1}: {e}")
                    break
                # For rate limit, respect retry_delay from API instead of fixed backoff
                if is_rate or "429" in msg:
                    retry_delay = _parse_retry_delay(str(e))
                    # Prefer API delay, else throttler interval
                    delay = retry_delay if retry_delay and retry_delay < 60 else 60.0 / settings.RATE_LIMIT_RPM
                    # On last attempt, don't sleep, will fallback or raise
                    if attempt < settings.MAX_RETRIES - 1:
                        logger.info(f"Rate limited (429), retrying in {delay}s (API delay)...")
                        time.sleep(delay)
                        continue
                    else:
                        break
                # For validation / other retryable, exponential backoff
                logger.warning(f"AI attempt {attempt+1}/{settings.MAX_RETRIES} failed: {e}")
                if attempt < settings.MAX_RETRIES - 1:
                    delay = settings.RETRY_BASE_DELAY * (2 ** attempt)
                    logger.info(f"Retrying in {delay}s...")
                    time.sleep(delay)
                else:
                    break
            except Exception as e:
                last_err = e
                logger.warning(f"AI unexpected error attempt {attempt+1}: {e}")
                if attempt < settings.MAX_RETRIES - 1:
                    delay = settings.RETRY_BASE_DELAY * (2 ** attempt)
                    time.sleep(delay)
                else:
                    break

        # all retries failed - fallback to mock for rate limit OR invalid JSON to keep demo usable
        if last_err and any(k in str(last_err).lower() for k in ["429", "quota", "exhausted", "prepayment", "unterminated", "expecting", "json", "validation"]):
            logger.warning(f"Fallback to mock after retries ({type(last_err).__name__}): {last_err}")
            try:
                mock_raw = self._mock_analyse(sender_name, sender_email, truncated, source)
                validated = self._validate(mock_raw)
                validated = self._enrich_routing(validated, message, source)
                _set_cached(sender_email, message, source, validated)
                return validated
            except Exception as me:
                logger.error(f"Mock fallback also failed: {me}")
        raise AIServiceError(f"AI analysis failed after {settings.MAX_RETRIES} retries: {last_err}")

    def _configure_client_for_key(self, api_key: str):
        """Re-configure generative AI client for the given key (for rotation)."""
        try:
            import google.generativeai as genai
            genai.configure(api_key=api_key)
            self._client = genai
            self._client_type = "genai"
            return True
        except Exception as e1:
            try:
                import importlib.util
                if importlib.util.find_spec("google.genai") is None:
                    return False
                from google import genai as new_genai
                self._client = new_genai.Client(api_key=api_key)
                self._client_type = "google-genai"
                return True
            except Exception as e2:
                logger.debug(f"Failed to configure client for rotated key: {e1} / {e2}")
                return False

    def _call_llm(self, sender_name: str, sender_email: str, message: str, source: str) -> dict:
        if self.is_mock:
            return self._mock_analyse(sender_name, sender_email, message, source)

        # If all keys exhausted, skip LLM entirely
        if self.api_keys and all(_is_key_exhausted(i) for i in range(len(self.api_keys))):
            raise AIServiceError("All Gemini keys exhausted (24h), using mock fallback")

        candidates = [self.model_name]
        for fb in ["gemini-3.6-flash", "gemini-2.0-flash", "gemini-1.5-flash"]:
            if fb not in candidates:
                candidates.append(fb)

        last_err = None
        # Rotate through all available API keys when hitting quota
        keys_to_try = self.api_keys if self.api_keys else [self.api_key]
        # Filter out exhausted keys for this call
        active_keys = [(i, k) for i, k in enumerate(keys_to_try) if not _is_key_exhausted(i)]
        if not active_keys:
            raise AIServiceError("All Gemini keys exhausted (24h), using mock fallback")
        for key_idx, api_key in active_keys:
            # Rate limiter per key (only for active keys)
            _throttle_for_key(key_idx)
            if key_idx != self._current_key_index:
                logger.info(f"Rotating to Gemini key {key_idx+1}/{len(keys_to_try)} due to previous quota")
                if not self._configure_client_for_key(api_key):
                    continue
                self._current_key_index = key_idx
            for model_name in candidates:
                try:
                    if self._client_type == "google-genai":
                        try:
                            from google.genai import types
                        except ModuleNotFoundError:
                            raise AIServiceError("google-genai not installed, skipping this client type")
                        prompt = f"""{SYSTEM_PROMPT}

Source: {source}
Sender: {sender_name} <{sender_email}>
Message:
{message}

Return ONLY JSON per schema."""
                        resp = self._client.models.generate_content(
                            model=model_name,
                            contents=prompt,
                            config=types.GenerateContentConfig(
                                temperature=0.2,
                                top_p=0.9,
                                max_output_tokens=settings.MAX_OUTPUT_TOKENS,
                                response_mime_type="application/json",
                            ),
                        )
                        text = resp.text if hasattr(resp, "text") and resp.text else str(resp)
                        text = self._strip_code_fences(text)
                        try:
                            data = json.loads(text)
                        except json.JSONDecodeError as je:
                            logger.warning(f"JSON parse failed (genai), raw: {text[:500]!r} err: {je}")
                            m = re.search(r"\{.*\}", text, re.DOTALL)
                            if m:
                                data = json.loads(m.group(0))
                            else:
                                raise
                        if key_idx > 0:
                            logger.info(f"Gemini key rotation succeeded on key {key_idx+1}")
                        if model_name != self.model_name:
                            logger.info(f"Gemini fallback model succeeded: {model_name}")
                        return data
                    else:
                        import google.generativeai as genai
                        combined_prompt = f"""{SYSTEM_PROMPT}

Source: {source}
Sender: {sender_name} <{sender_email}>
Message:
{message}

Return ONLY valid JSON per schema. No markdown, no explanation, escape quotes in strings."""
                        try:
                            model = genai.GenerativeModel(
                                model_name,
                                generation_config={
                                    "temperature": 0.1,
                                    "top_p": 0.9,
                                    "max_output_tokens": settings.MAX_OUTPUT_TOKENS,
                                },
                            )
                            resp = model.generate_content(combined_prompt)
                        except Exception as e:
                            logger.warning(f"Generation config failed for {model_name}: {e} — retrying bare")
                            model = genai.GenerativeModel(model_name)
                            resp = model.generate_content(combined_prompt)
                        text = self._extract_text(resp)
                        text = self._strip_code_fences(text)
                        # Robust JSON extraction: find first { to last }
                        try:
                            data = json.loads(text)
                        except json.JSONDecodeError as je:
                            logger.warning(f"JSON parse failed, raw (first 500 chars): {text[:500]!r} error: {je}")
                            # Try to extract JSON object via regex
                            m = re.search(r"\{.*\}", text, re.DOTALL)
                            if m:
                                try:
                                    data = json.loads(m.group(0))
                                except:
                                    # Try fixing common issues: trailing commas, single quotes
                                    fixed = m.group(0).replace("'", '"').replace(",}", "}").replace(",]", "]")
                                    data = json.loads(fixed)
                            else:
                                raise
                        if key_idx > 0:
                            logger.info(f"Gemini key rotation succeeded on key {key_idx+1}")
                        if model_name != self.model_name:
                            logger.info(f"Gemini fallback model succeeded: {model_name}")
                        return data
                except json.JSONDecodeError:
                    raise
                except Exception as e:
                    msg = str(e).lower()
                    if "404" in msg or "not found" in msg or "unsupported" in msg or "not supported" in msg:
                        logger.warning(f"Model {model_name} not available: {e} — trying fallback")
                        last_err = e
                        continue
                    if "429" in msg or "quota" in msg or "rate" in msg or "prepayment" in msg:
                        is_quota = any(k in msg for k in ["perday", "preday", "prepayment", "quota", "generateRequestsPerDay".lower()])
                        if is_quota:
                            _mark_key_exhausted(key_idx)
                        # Rate limit hit for this key -> break model loop and try next key
                        logger.warning(f"{'Quota' if is_quota else 'Rate'} hit on key {key_idx+1}/{len(keys_to_try)} for model {model_name}: {e}")
                        last_err = AIServiceError(f"Retryable LLM error: {e}")
                        break  # break model loop -> outer key loop will continue to next key
                    if "timeout" in msg or "deadline" in msg:
                        raise AIServiceError(f"Retryable LLM error: {e}") from e
                    if "404" in msg or "not found" in msg:
                        last_err = e
                        continue
                    raise AIServiceError(f"LLM call failed: {e}") from e
            # If we broke due to 429, continue to next key; otherwise models exhausted for this key
            if last_err and isinstance(last_err, AIServiceError) and "429" in str(last_err).lower():
                # Continue to next key (if any)
                if key_idx < len(keys_to_try) - 1:
                    continue
                else:
                    # All keys exhausted with quota
                    raise last_err
        raise AIServiceError(f"All Gemini keys/models failed. Last error: {last_err}")

    def _extract_text(self, resp) -> str:
        # google-generativeai response handling
        try:
            if hasattr(resp, "text") and resp.text:
                return resp.text
            # fallback: candidates
            if hasattr(resp, "candidates") and resp.candidates:
                parts = resp.candidates[0].content.parts
                return "".join(p.text for p in parts if hasattr(p, "text"))
            return str(resp)
        except Exception as e:
            raise AIServiceError(f"Failed to extract LLM text: {e}") from e

    def _strip_code_fences(self, text: str) -> str:
        t = text.strip()
        # remove ```json ... ``` or ``` ... ```
        if t.startswith("```"):
            # find first newline after opening fence and last fence
            t = re.sub(r"^```(?:json)?\s*", "", t)
            t = re.sub(r"\s*```$", "", t)
        return t.strip()

    def _validate(self, data: dict) -> AIAnalysis:
        # Pydantic strict validation
        # Coerce confidence to float if needed
        if "confidence" in data and isinstance(data["confidence"], str):
            try:
                data["confidence"] = float(data["confidence"])
            except:
                pass
        # Normalize priority if string
        if "priority" in data and isinstance(data["priority"], str):
            data["priority"] = data["priority"].lower().strip() or None
            if data["priority"] not in ("low", "medium", "high"):
                data["priority"] = None
        # Ensure intent_keywords present
        if "intent_keywords" not in data or data["intent_keywords"] is None:
            data["intent_keywords"] = []
        analysis = AIAnalysis.model_validate(data)
        return analysis

    def _enrich_routing(self, analysis: AIAnalysis, original_message: str, source: str = None) -> AIAnalysis:
        """Option B + Opsi A: compute suggested_team via TF-IDF embedding from LLM keywords+intent+source (scalable, no manual lists)."""
        try:
            from app.services.routing_service import route_team

            # Build query from keywords + intent + classification
            query_parts = []
            if analysis.intent_keywords:
                query_parts.append(" ".join(analysis.intent_keywords))
            if analysis.intent:
                query_parts.append(analysis.intent)
            query_parts.append(analysis.classification.value if hasattr(analysis.classification, "value") else str(analysis.classification))
            query = " ".join(query_parts) or original_message
            team = route_team(query, analysis.classification, source=source)
            analysis.suggested_team = team
        except Exception as e:
            logger.warning(f"Routing enrichment failed: {e}")
        return analysis

    def _derive_mock_keywords(self, message: str, max_k: int = 5) -> list[str]:
        # Simple keyword extractor for mock — no manual per-role lists, just message-derived
        import re as _re

        stop = {"the", "and", "for", "with", "are", "our", "you", "your", "have", "has", "this", "that", "from", "about", "please", "thanks", "hello", "hi", "dear", "we", "i", "am", "is", "a", "an", "to", "of", "in", "on", "at"}
        toks = _re.findall(r"[a-zA-Z]{3,}", message.lower())
        freq: dict[str, int] = {}
        for t in toks:
            if t not in stop and len(t) > 3:
                freq[t] = freq.get(t, 0) + 1
        # sort by freq then appearance
        sorted_k = sorted(freq.items(), key=lambda x: (-x[1], toks.index(x[0]) if x[0] in toks else 999))
        kws = [k for k, _ in sorted_k[:max_k]]
        return kws or ["enquiry"]

    def _derive_mock_priority(self, message: str, classification: str) -> str:
        low = message.lower()
        if any(w in low for w in ["urgent", "asap", "immediately", "blocking", "critical", "error 500", "not working", "broken"]):
            return "high"
        if classification == "insufficient_information":
            return "low"
        if classification == "junk":
            return "low"
        return "medium"

    def _mock_draft(self, classification: str, sender_name: str, company: Optional[str], intent: str, kws: list[str], missing: list[str], source: str) -> Optional[str]:
        """LLM-like varied draft for mock fallback — deterministic but contextual, not single template."""
        name = sender_name or "there"
        first = sender_name.split()[0] if sender_name and sender_name.strip() else "there"
        # deterministic variation index from message hash
        h = int(hashlib.sha256(f"{intent}{company}{source}".encode()).hexdigest()[:8], 16) % 3
        kw = ", ".join(kws[:2]) if kws else "your inquiry"
        if classification == "junk":
            return None
        if classification == "insufficient_information":
            templates = [
                f"Hi {first}, thanks for your interest! Could you share a bit about your company and the challenge you're hoping to solve?",
                f"Hello {first}, appreciate your note about {kw}. What company are you with and what timeline are you considering?",
                f"Hi {first}, could you tell us more about your use case and company size so we can point you to the right team?",
            ]
            return templates[h]
        if classification == "support":
            # support draft empathizes and asks for details
            issue = kws[0] if kws else "the issue"
            templates = [
                f"Hi {first}, sorry you're experiencing {issue} — our support team will look into it right away. Could you share any error details or order ID?",
                f"Hello {first}, thanks for flagging {kw}. We'll investigate shortly — could you send a screenshot or more context?",
                f"Hi {first}, sorry to hear about {issue}. Our team is on it — any additional details (steps to reproduce, account) would help.",
            ]
            return templates[h]
        if classification == "other":
            # HR / career / general other — never ask budget
            comp = company or "BEDA"
            templates = [
                f"Hi {first}, thanks for your interest in joining {comp}. Our HR team will review your inquiry and share current openings — feel free to send your CV and preferred role.",
                f"Hello {first}, appreciate you reaching out about opportunities at {comp}. We'll forward this to HR and get back with next steps.",
                f"Hi {first}, thanks for considering {comp} for your next role. Could you share your CV and which position interests you?",
            ]
            return templates[h]
        # sales default — contextual with company/kws/missing
        miss = missing[0] if missing else "timeline"
        comp = f" at {company}" if company else ""
        templates = [
            f"Hi {first}, thanks for exploring {kw}{comp}. Could you share your {miss} and budget range so we can tailor a proposal?",
            f"Hello {first}, appreciate your interest in {kw}{comp} — what's your expected {miss} and budget?",
            f"Hi {first}, great to hear about {kw}{comp}. Could you tell us more about your {miss} and use case?",
        ]
        return templates[h]

    # ---------- Deterministic Mock (LLM-like, generates keywords from message, not manual role lists) ----------
    def _mock_analyse(self, sender_name: str, sender_email: str, message: str, source: str) -> dict:
        """
        Lightweight heuristic mock that mimics LLM behavior deterministically.
        Used when no API key is set, or for tests. Generates intent_keywords from message itself (scalable).
        """
        low = message.lower().strip()
        # Very short / vague -> insufficient_information
        if len(low) < 30 and not any(k in low for k in ["price", "pricing", "demo", "support", "help", "issue", "bug", "error"]):
            # Check if it's basically "hi interested"
            vague_phrases = ["interested in your services", "interested", "hello", "hi,", "more info", "tell me more"]
            if any(p in low for p in vague_phrases) or len(low.split()) < 8:
                kws = self._derive_mock_keywords(message) or ["vague", "enquiry"]
                return {
                    "classification": "insufficient_information",
                    "confidence": 0.91,
                    "contact": {"name": sender_name, "email": sender_email, "phone": None},
                    "company": {"name": None, "size": None},
                    "intent": "Vague enquiry, insufficient details",
                    "intent_keywords": kws,
                    "priority": "low",
                    "missing_information": ["company", "business_need", "contact_details"],
                    "recommended_action": "REQUEST_MORE_INFORMATION",
                    "draft_response": self._mock_draft("insufficient_information", sender_name, None, "Vague enquiry, insufficient details", kws, ["company", "business_need"], source),
                }
        # Signals — used only for mock classification, not for routing (routing is embedding-based)
        sales_signals = ["interested", "pricing", "price", "quote", "demo", "automation for", "looking for", "partnership", "proposal", "budget", "timeline", "employees"]
        support_strong = ["issue", "bug", "error", "not working", "broken", "complaint", "refund", "ticket", "can't", "cannot", "help me", "not able", "failed to"]
        # If message is strongly support (has strong keywords) -> support, regardless of sales signals
        if any(k in low for k in support_strong):
            kws = self._derive_mock_keywords(message)
            comp = self._extract_company(message)
            return {
                "classification": "support",
                "confidence": 0.88,
                "contact": {"name": sender_name, "email": sender_email, "phone": self._extract_phone(message)},
                "company": {"name": comp or None, "size": self._extract_company_size(message)},
                "intent": "Customer seeking support assistance",
                "intent_keywords": kws,
                "priority": self._derive_mock_priority(message, "support"),
                "missing_information": [] if "error" in low or "issue" in low else ["order_id", "details"],
                "recommended_action": "CREATE_SUPPORT_CASE",
                "draft_response": self._mock_draft("support", sender_name, comp, "Customer seeking support assistance", kws, ["details"], source),
            }
        # Generic "support" / "help" alone is ambiguous; only treat as support if no strong sales signals
        support_generic = ["support", "help"]
        if any(k in low for k in support_generic) and not any(s in low for s in sales_signals):
            kws = self._derive_mock_keywords(message)
            comp = self._extract_company(message)
            return {
                "classification": "support",
                "confidence": 0.82,
                "contact": {"name": sender_name, "email": sender_email, "phone": self._extract_phone(message)},
                "company": {"name": comp or None, "size": self._extract_company_size(message)},
                "intent": "Customer seeking support assistance",
                "intent_keywords": kws,
                "priority": self._derive_mock_priority(message, "support"),
                "missing_information": ["details"],
                "recommended_action": "CREATE_SUPPORT_CASE",
                "draft_response": self._mock_draft("support", sender_name, comp, "Customer seeking support assistance", kws, ["details"], source),
            }
        # Junk signals (LLM would catch, mock also)
        junk_signals = ["lottery", "winner", "congratulations you won", "earn $", "make money fast"]
        if any(k in low for k in junk_signals):
            return {
                "classification": "junk",
                "confidence": 0.96,
                "contact": {"name": sender_name, "email": sender_email, "phone": None},
                "company": {"name": None, "size": None},
                "intent": "Spam/promotional content",
                "intent_keywords": ["spam", "lottery", "winner"] if "lottery" in low else self._derive_mock_keywords(message),
                "priority": "low",
                "missing_information": [],
                "recommended_action": "MARK_AS_JUNK",
                "draft_response": None,
            }
        # HR / career / job at BEDA — must be before default sales (sales_signals contains generic "interested")
        # use strong HR signals to avoid misclassifying partnership "opportunities" as HR
        hr_strong = ["job", "career", "hiring", "recruitment", "vacancy", "employment", "cv", "resume", "openings", "opening"]
        if any(k in low for k in hr_strong):
            kws = self._derive_mock_keywords(message)
            # ensure BEDA company captured for HR routing
            comp = self._extract_company(message) or ("BEDA" if "beda" in low else None)
            return {
                "classification": "other",
                "confidence": 0.90,
                "contact": {"name": sender_name, "email": sender_email, "phone": self._extract_phone(message)},
                "company": {"name": comp, "size": self._extract_company_size(message)},
                "intent": "Interested in job/career opportunities at BEDA",
                "intent_keywords": kws,
                "priority": "low",
                "missing_information": ["resume", "position"],
                "recommended_action": "REQUEST_MORE_INFORMATION",
                "draft_response": self._mock_draft("other", sender_name, comp or "BEDA", "Interested in job/career opportunities", kws, ["resume"], source),
            }
        # Default -> sales
        company = self._extract_company(message)
        size = self._extract_company_size(message)
        missing = []
        if not company:
            missing.append("company")
        if "budget" not in low:
            missing.append("budget")
        if "timeline" not in low and "when" not in low:
            missing.append("timeline")
        # keep limited missing
        missing = missing[:3]
        intent = self._summarize_intent(message)
        kws = self._derive_mock_keywords(message)
        return {
            "classification": "sales",
            "confidence": 0.94 if company else 0.78,
            "contact": {"name": sender_name, "email": sender_email, "phone": self._extract_phone(message)},
            "company": {"name": company, "size": size},
            "intent": intent,
            "intent_keywords": kws,
            "priority": self._derive_mock_priority(message, "sales"),
            "missing_information": missing,
            "recommended_action": "CREATE_LEAD",
            "draft_response": self._mock_draft("sales", sender_name, company, intent, kws, missing, source),
        }

    def _extract_phone(self, text: str) -> Optional[str]:
        m = re.search(r"(\+?\d[\d \-\(\)]{7,}\d)", text)
        if m:
            return m.group(1).strip()
        return None

    def _extract_company(self, text: str) -> Optional[str]:
        # naive: look for "at <Company>" or "from <Company>" or "company with ..." or capitalized words after "we are"
        m = re.search(r"\b(?:at|from|company|team at)\s+([A-Z][A-Za-z0-9 &]+)", text)
        if m:
            cand = m.group(1).strip().split(".")[0].split(",")[0].strip()
            # trim trailing common words
            cand = re.sub(r"\s+with\s+.*$", "", cand, flags=re.I).strip()
            if len(cand) > 1 and len(cand) < 50:
                return cand
        # fallback: look for "Acme" style - capitalized word before comma?
        return None

    def _extract_company_size(self, text: str) -> Optional[str]:
        m = re.search(r"(\d+\s*(?:employees|people|staff|members))", text, re.I)
        if m:
            return m.group(1)
        m2 = re.search(r"approximately\s+(\d+)", text, re.I)
        if m2:
            return f"{m2.group(1)} employees"
        return None

    def _summarize_intent(self, text: str) -> str:
        # first sentence or 120 chars
        s = text.strip().split(".")[0].strip()
        if len(s) > 120:
            s = s[:120].rsplit(" ", 1)[0] + "..."
        return s or "Business enquiry"

# Singleton
_ai_service: Optional[AIService] = None

def get_ai_service() -> AIService:
    global _ai_service
    if _ai_service is None:
        _ai_service = AIService()
    return _ai_service

def reset_ai_service(clear_cache: bool = False):
    global _ai_service, _response_cache, _key_quota_exhausted, _last_call_per_key
    _ai_service = None
    if clear_cache:
        _response_cache.clear()
        _key_quota_exhausted.clear()
        _last_call_per_key.clear()
